services:
  - type: web
    name: campusconnect-api-gateway
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: "3000"
      - key: USER_SERVICE_URL
        value: https://campusconnect-user-service.onrender.com
      - key: PRODUCT_SERVICE_URL
        value: https://campusconnect-product-service.onrender.com
      - key: ORDER_SERVICE_URL
        value: https://campusconnect-order-service.onrender.com

  - type: web
    name: campusconnect-user-service
    env: docker
    dockerfilePath: ./user-service/Dockerfile
    dockerContext: ./user-service
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: "3001"

  - type: web
    name: campusconnect-product-service
    env: docker
    dockerfilePath: ./product-service/Dockerfile
    dockerContext: ./product-service
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: "3002"

  - type: web
    name: campusconnect-order-service
    env: docker
    dockerfilePath: ./order-service/Dockerfile
    dockerContext: ./order-service
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: "3003"
      - key: USER_SERVICE_URL
        value: https://campusconnect-user-service.onrender.com
      - key: PRODUCT_SERVICE_URL
        value: https://campusconnect-product-service.onrender.com
