spring.application.name=student-api

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://studentadmin:qC!S4nSFU2d7scm@cluster0.h2gtxpa.mongodb.net/studentdb?retryWrites=true&w=majority}
spring.mongodb.uri=${MONGO_URI:mongodb+srv://studentadmin:qC!S4nSFU2d7scm@cluster0.h2gtxpa.mongodb.net/studentdb?retryWrites=true&w=majority}

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
server.address=0.0.0.0