apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: lab8
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCT_SERVICE_PORT
