apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: lab8
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: user-service
