services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb:27017/studentdb
    depends_on:
      - mongodb
    networks:
      - student-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - student-mongo-data:/data/db
    networks:
      - student-network

networks:
  student-network:
    driver: bridge

volumes:
  student-mongo-data:
